name: LutekRest
version: 1.0.0
api: [3.0.0, 4.0.0, 5.0.0]
main: LutekRest\LutekDev\LutekRest
load: STARTUP
author: LutekDev
description: API REST Oficial do LutekDev#7002
website: github.com/lutekdev

# English #
#
# For the security of your Server and Plug-ins. Don't mess with this API REST.
# This API REST was created by me, LutekDev#7002, in order to help the Community.
# And also to me creator / Developer of Plug-ins.
# In case of exchanging information, keep in mind that your server may crash.
#
# Portuguese #
#
# Pela segurança do seu Servidor e dos Plug-ins. Não mexa nessa API REST.
# Essa API REST foi criada por mim, LutekDev#7002, no fim de ajudar a Comunidade.
# E também a mim criador / Desenvolvedor de Plug-ins.
# Em caso de trocas de informações, tenham em mente que seu servidor pode crashar.

